version: "3.4"
services: 
    app:
        container_name: assessment
        restart: always
        build:
          context: .
          # network: host
        ports: 
          - "3000:9000"
    mongo:
        container_name: mongo
        image: mongo
        volumes:
          - ./data:/data/db